### DISCUSSION TITLE
disable compile on save

### DISCUSSION THREAD

**Discussion by Idobenhamo** [nvarner/typst-lsp#158] [Q&A] [answered]
Hi,
How i can disable the compile on save option?

**Comment by nvarner** [comment, marked as answer]
If you're using the VS Code/VS Codium extension, you can change the "Export PDF" setting to "never". On other clients, that corresponds to setting `exportPdf` to `never` in the language server configuration.

**Reply by Idobenhamo** [reply]
Thank you! 
This is how i did it for helix.
```toml
[language-server.typst-lsp]
command = "typst-lsp" 
config = { exportPdf = "never" }
```
