### ISSUE TITLE
onType option not woking in Helix editor

### ISSUE THREAD

**Issue by devanlooches** [nvarner/typst-lsp#418]
- **Component**: 
    - LSP (used with other editor)
- **LSP version**: 0.12.1, commit 0d5b9330a1d515fa47456e755f751ea4056282b8 (Typst version 0.10.0)
- **OS version and name**: macOS 14.0

- I am on the [latest](https://github.com/nvarner/typst-lsp/tags) stable version of the extension/LSP.
- I have searched the [issues](https://github.com/nvarner/typst-lsp/issues) of this repo and believe that this is not a duplicate.

## Issue

Here is my lsp configuration for the Helix editor:

```toml
[[language]]
name = "typst"
scope = "source.typst"
injection-regex = "^typ(st)?$"
file-types = ["typ"]
roots = []
language-servers = ["typst-lsp", "prosemd"]
[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'$' = '$'

[language-server.typst-lsp]
command = "typst-lsp"
config = { exportPdf = "onType" }
roots = []
comment-token = "//"
indent = { tab-width = 2, unit = " " }
formatter = { command = "typstfmt" }
text-width = 100
rulers = [100]
soft-wrap.wrap-at-text-width = true
```

Even though I set the export-pdf option to onType, it does not compile onType and instead only compiles onSave.
Thanks in advance for any help!
