### ISSUE TITLE
Document configuration options (pdf export) for other editors

### ISSUE THREAD

**Issue by kanashimia** [nvarner/typst-lsp#47]
For example in helix you have to add this to the `languages.toml`: 

```toml
[[language]]
name = "typst"
scope = "source.typst"
injection-regex = "^typ(st)?$"
file-types = ["typ"]
roots = []
comment-token = "//"
language-server = { command = "typst-lsp" }
config = { exportPdf = "onType"}
```

Should note specifically what can be passed as a `config`.

I was able to find this only by looking through https://github.com/nvarner/typst-lsp/blob/5887fe041ef0bdfa15f4a15c76e636ea6265d90a/addons/vscode/package.json#L22-L39
You can just add a reference to that file.
