### ISSUE TITLE
"et al." not applied after the first use of citation

### ISSUE THREAD

**Issue by miles-1** [nvarner/typst-lsp#512]
- **Component**:
    - VSCode Extension
- **Extension version**: 0.13.0
- **OS version and name**: macOS 14.5
- I am on the [latest](https://github.com/nvarner/typst-lsp/tags) stable version of the extension/LSP.
- I have searched the [issues](https://github.com/nvarner/typst-lsp/issues) of this repo and believe that this is not a duplicate.

## Issue
If using a style like `"apa"` in `bibliography`, the first instance of a citation correctly truncates the number of authors with "et al.", but any additional instances of that citation include all author names.

Thanks very much for your work to maintain this repo! It is much appreciated.

**Comment by yochem** [comment]
This should probably be transferred to [typst/typst](https://github.com/typst/typst), [typst/hayagriva](https://github.com/typst/hayagriva) or [citation-style/styles](https://github.com/citation-style-language/styles). Could you provide a MWE?

**Comment by miles-1** [comment]
No, this is not an issue for typst (or tinymist, which I have since switched to because of this issue), just for the typst-lsp vscode extension.

MWE is just as I said, use a citation twice with `"apa"` for bibliography. For a file `citations.yml` containing the following:

```yml
Roche_2012a:
    type: Article
    title: "Linking community and disease ecology: the impact of biodiversity on pathogen transmission"
    author: ['Roche, Benjamin', 'Dobson, Andrew P.', 'Guégan, Jean-François', 'Rohani, Pejman']
    date: 2012-10
    page-range: 2807-2813
    parent:
        title:
            value: "{Phil. Trans. R. Soc. B}"
        volume: 367
```

... an a typst file containing the following:

```typst
@Roche_2012a

@Roche_2012a

#bibliography(
  "citations.yml",
  style: "apa"
)
```

... typst online and tinymist both render the two citations as `(Roche et al, 2012)`, but typst-lsp adds all authors but just to the second citation.
